// Start Header

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: api.proto

package main

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MoveMessage_MoveEnum int32

const (
	MoveMessage_NOOP       MoveMessage_MoveEnum = 0
	MoveMessage_MOVE_LEFT  MoveMessage_MoveEnum = 1
	MoveMessage_MOVE_RIGHT MoveMessage_MoveEnum = 2
	MoveMessage_MOVE_UP    MoveMessage_MoveEnum = 3
	MoveMessage_MOVE_DOWN  MoveMessage_MoveEnum = 4
	MoveMessage_PLACE_MARK MoveMessage_MoveEnum = 5
)

// Enum value maps for MoveMessage_MoveEnum.
var (
	MoveMessage_MoveEnum_name = map[int32]string{
		0: "NOOP",
		1: "MOVE_LEFT",
		2: "MOVE_RIGHT",
		3: "MOVE_UP",
		4: "MOVE_DOWN",
		5: "PLACE_MARK",
	}
	MoveMessage_MoveEnum_value = map[string]int32{
		"NOOP":       0,
		"MOVE_LEFT":  1,
		"MOVE_RIGHT": 2,
		"MOVE_UP":    3,
		"MOVE_DOWN":  4,
		"PLACE_MARK": 5,
	}
)

func (x MoveMessage_MoveEnum) Enum() *MoveMessage_MoveEnum {
	p := new(MoveMessage_MoveEnum)
	*p = x
	return p
}

func (x MoveMessage_MoveEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MoveMessage_MoveEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (MoveMessage_MoveEnum) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x MoveMessage_MoveEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MoveMessage_MoveEnum.Descriptor instead.
func (MoveMessage_MoveEnum) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

// Start Message Definitions
type MoveMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MoveRequest MoveMessage_MoveEnum `protobuf:"varint,1,opt,name=moveRequest,proto3,enum=main.MoveMessage_MoveEnum" json:"moveRequest,omitempty"`
}

func (x *MoveMessage) Reset() {
	*x = MoveMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveMessage) ProtoMessage() {}

func (x *MoveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveMessage.ProtoReflect.Descriptor instead.
func (*MoveMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *MoveMessage) GetMoveRequest() MoveMessage_MoveEnum {
	if x != nil {
		return x.MoveRequest
	}
	return MoveMessage_NOOP
}

var File_api_proto protoreflect.FileDescriptor

var file_api_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69,
	0x6e, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0xac, 0x01, 0x0a, 0x0b, 0x4d,
	0x6f, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x6d, 0x6f,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1a, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x0b, 0x6d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5f, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65,
	0x45, 0x6e, 0x75, 0x6d, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4f, 0x50, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x01, 0x12, 0x0e, 0x0a,
	0x0a, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x52, 0x49, 0x47, 0x48, 0x54, 0x10, 0x02, 0x12, 0x0b, 0x0a,
	0x07, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x55, 0x50, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x4f,
	0x56, 0x45, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x4c, 0x41,
	0x43, 0x45, 0x5f, 0x4d, 0x41, 0x52, 0x4b, 0x10, 0x05, 0x32, 0x3e, 0x0a, 0x0b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x2f, 0x0a, 0x0b, 0x50, 0x65, 0x72, 0x66,
	0x6f, 0x72, 0x6d, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4d,
	0x6f, 0x76, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0b, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData = file_api_proto_rawDesc
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_rawDescData)
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_goTypes = []interface{}{
	(MoveMessage_MoveEnum)(0), // 0: main.MoveMessage.MoveEnum
	(*Empty)(nil),             // 1: main.Empty
	(*MoveMessage)(nil),       // 2: main.MoveMessage
}
var file_api_proto_depIdxs = []int32{
	0, // 0: main.MoveMessage.moveRequest:type_name -> main.MoveMessage.MoveEnum
	2, // 1: main.RequestMove.PerformMove:input_type -> main.MoveMessage
	1, // 2: main.RequestMove.PerformMove:output_type -> main.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_rawDesc = nil
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RequestMoveClient is the client API for RequestMove service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RequestMoveClient interface {
	PerformMove(ctx context.Context, in *MoveMessage, opts ...grpc.CallOption) (*Empty, error)
}

type requestMoveClient struct {
	cc grpc.ClientConnInterface
}

func NewRequestMoveClient(cc grpc.ClientConnInterface) RequestMoveClient {
	return &requestMoveClient{cc}
}

func (c *requestMoveClient) PerformMove(ctx context.Context, in *MoveMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/main.RequestMove/PerformMove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequestMoveServer is the server API for RequestMove service.
type RequestMoveServer interface {
	PerformMove(context.Context, *MoveMessage) (*Empty, error)
}

// UnimplementedRequestMoveServer can be embedded to have forward compatible implementations.
type UnimplementedRequestMoveServer struct {
}

func (*UnimplementedRequestMoveServer) PerformMove(context.Context, *MoveMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PerformMove not implemented")
}

func RegisterRequestMoveServer(s *grpc.Server, srv RequestMoveServer) {
	s.RegisterService(&_RequestMove_serviceDesc, srv)
}

func _RequestMove_PerformMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestMoveServer).PerformMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.RequestMove/PerformMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestMoveServer).PerformMove(ctx, req.(*MoveMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _RequestMove_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.RequestMove",
	HandlerType: (*RequestMoveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PerformMove",
			Handler:    _RequestMove_PerformMove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
